[package]
name = "plumo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tar = "0.4"
walkdir = "2.3"
aes-gcm = "0.10"
argon2 = "0.5"
rand = "0.8"
rpassword = "5.0"
